package com.netralabs.domain;

public enum Subcategory {
  PDF_SYNTAX, FONTS, CONTENT, EMBEDDED_FILES, NATURAL_LANGUAGE,
  STRUCTURE_ELEMENTS, STRUCTURE_TREE, ROLE_MAPPING, ALTERNATIVE_DESCRIPTIONS,
  PDFUA_IDENTIFICATION, XMP_DC, DOC_INFO, LANGUAGE,
  OUTPUT_INTENT, SECURITY_AND_SIGNATURES, OUTLINES

}
