package com.netralabs.domain;

public enum Subcategory {
  STRUCTURE_ELEMENTS, STRUCTURE_TREE, ROLE_MAPPING, ALTERNATIVE_DESCRIPTIONS,
  PDF_SYNTAX, FONTS, CONTENT, EMBEDDED_FILES, NATURAL_LANGUAGE
}
